/** @type {import('prettier').Config} */
module.exports = {
  semi: true,
  trailingComma: 'all',
  singleQuote: true,
  jsxSingleQuote: true,
  printWidth: 100,
  useTabs: false,
  tabWidth: 2,
  arrowParens: 'always',
  endOfLine: 'if',
  bracketSpacing: false,
  bracketSameL1ine: false,
  importOrder: [
    '^(react/(.*)$)|^(react$)',
    '^(next/(.*)$)|^(next$)',
    '<THIRD_PARTY_MODULES>',
    '',
    '^types$',
    '^@/types/(.*)$',
    '^@/config/(.*)$',
    '^@/lib/(.*)$',
    '^@/hooks/(.*)$',
    '^@/components/ui/(.*)$',
    '^@/components/(.*)$',
    '^@/styles/(.*)$',
    '^@/app/(.*)$',
    '',
    '^[./]',
  ],
  importOrderSeparation: false,
  importOrderSortSpecifiers: true,
  importOrderBuiltinModulesToTop: true,
  importOrderParserPlugins: ['typescript', 'jsx', 'decorators-legacy'],
  importOrderMergeDuplicateImports: true,
  importOrderCombineTypeAndValueImports: true,
  plugins: ['@ianvs/prettier-plugin-sort-imports'],
};

// /** @type {import('prettier').Config} */
// module.exports = {
//   trailingComma: 'es5',
//   tabWidth: 2,
//   semi: true,
//   singleQuote: true,
//   jsxSingleQuote: true,
//   printWidth: 100,
//   eslintIntegration: true,
//   endOfLine: 'auto',
//   useTabs: false,
//   arrowParens: 'always',
//   importOrder: [
//     '^(react/(.*)$)|^(react$)',
//     '^(next/(.*)$)|^(next$)',
//     '<THIRD_PARTY_MODULES>',
//     '',
//     '^types$',
//     '^@/types/(.*)$',
//     '^@/config/(.*)$',
//     '^@/lib/(.*)$',
//     '^@/hooks/(.*)$',
//     '^@/components/ui/(.*)$',
//     '^@/components/(.*)$',
//     '^@/styles/(.*)$',
//     '^@/app/(.*)$',
//     '',
//     '^[./]',
//   ],
//   importOrderSeparation: false,
//   importOrderSortSpecifiers: true,
//   importOrderBuiltinModulesToTop: true,
//   importOrderParserPlugins: ['typescript', 'jsx', 'decorators-legacy'],
//   importOrderMergeDuplicateImports: true,
//   importOrderCombineTypeAndValueImports: true,
//   plugins: ['@ianvs/prettier-plugin-sort-imports'],
// };
