/** @type {import('prettier').Config} */
module.exports = {
  trailingComma: 'es5',
  tabWidth: 2,
  semi: true,
  singleQuote: true,
  jsxSingleQuote: true,
  printWidth: 100,
  eslintIntegration: true,
  endOfLine: 'auto',
  parser: 'typescript',
  useTabs: false,
  arrowParens: 'always',
};

// /** @type {import('prettier').Config} */
// module.exports = {
//   trailingComma: 'es5',
//   tabWidth: 2,
//   semi: true,
//   singleQuote: true,
//   jsxSingleQuote: true,
//   printWidth: 100,
//   eslintIntegration: true,
//   endOfLine: 'auto',
//   useTabs: false,
//   arrowParens: 'always',
//   importOrder: [
//     '^(react/(.*)$)|^(react$)',
//     '^(next/(.*)$)|^(next$)',
//     '<THIRD_PARTY_MODULES>',
//     '',
//     '^types$',
//     '^@/types/(.*)$',
//     '^@/config/(.*)$',
//     '^@/lib/(.*)$',
//     '^@/hooks/(.*)$',
//     '^@/components/ui/(.*)$',
//     '^@/components/(.*)$',
//     '^@/styles/(.*)$',
//     '^@/app/(.*)$',
//     '',
//     '^[./]',
//   ],
//   importOrderSeparation: false,
//   importOrderSortSpecifiers: true,
//   importOrderBuiltinModulesToTop: true,
//   importOrderParserPlugins: ['typescript', 'jsx', 'decorators-legacy'],
//   importOrderMergeDuplicateImports: true,
//   importOrderCombineTypeAndValueImports: true,
//   plugins: ['@ianvs/prettier-plugin-sort-imports'],
// };
