export const photos = [
  {
    index: 1,
    src: '/facilities/facilities01.jpg',
    width: 1,
    height: 1,
    alt: '방석',
    original: '/facilities/facilities01.jpg',
    caption: '임시 내부시설 공개',
  },
  {
    index: 2,
    src: '/facilities/facilities02.jpg',
    width: 1,
    height: 1,
    alt: '입구',
    original: '/facilities/facilities02.jpg',
    caption: '임시 내부시설 공개',
  },
  {
    index: 3,
    src: '/facilities/facilities03.jpg',
    width: 1,
    height: 1,
    alt: '진입',
    original: '/facilities/facilities03.jpg',
    caption: '임시 내부시설 공개',
  },
  {
    index: 4,
    src: '/facilities/facilities04.jpg',
    width: 1,
    height: 1,
    alt: '대기석1',
    original: '/facilities/facilities04.jpg',
    caption: '임시 내부시설 공개',
  },
  {
    index: 5,
    src: '/facilities/facilities05.jpg',
    width: 1,
    height: 1,
    alt: '대기석2',
    original: '/facilities/facilities05.jpg',
    caption: '임시 내부시설 공개',
  },
  {
    index: 6,
    src: '/facilities/facilities06.jpg',
    width: 1,
    height: 1,
    alt: '심리발달센터',
    original: '/facilities/facilities06.jpg',
    caption: '임시 내부시설 공개',
  },
];
