const facilities = [
  // {
  //   index: 1,
  //   src: '/facilities/facilities01.jpg',
  //   width: 1,
  //   height: 1,
  //   alt: '방석',
  //   original: '/facilities/facilities01.jpg',
  //   caption: '초기 방문자 선물, 나란히 젓가락',
  // },
  // {
  //   index: 2,
  //   src: '/facilities/facilities02.jpg',
  //   width: 1,
  //   height: 1,
  //   alt: '입구',
  //   original: '/facilities/facilities02.jpg',
  //   caption: '내부시설 공개',
  // },
  // {
  //   index: 3,
  //   src: '/facilities/facilities03.jpg',
  //   width: 1,
  //   height: 1,
  //   alt: '진입',
  //   original: '/facilities/facilities03.jpg',
  //   caption: '내부시설 공개',
  // },
  // {
  //   index: 4,
  //   src: '/facilities/facilities04.jpg',
  //   width: 1,
  //   height: 1,
  //   alt: '대기석1',
  //   original: '/facilities/facilities04.jpg',
  //   caption: '내부시설 공개',
  // },
  // {
  //   index: 5,
  //   src: '/facilities/facilities05.jpg',
  //   width: 1,
  //   height: 1,
  //   alt: '대기석2',
  //   original: '/facilities/facilities05.jpg',
  //   caption: '내부시설 공개',
  // },
  // {
  //   index: 6,
  //   src: '/facilities/facilities06.jpg',
  //   width: 1,
  //   height: 1,
  //   alt: '심리발달센터',
  //   original: '/facilities/facilities06.jpg',
  //   caption: '내부시설 공개',
  // },
  // {
  //   index: 7,
  //   src: '/facilities/facilities07.jpg',
  //   width: 3,
  //   height: 2,
  //   alt: '간판',
  //   original: '/facilities/facilities07.jpg',
  //   caption: '간판',
  // },
];

const hospitals = [
  // {
  //   index: 1,
  //   src: '/hospital/hospital01.jpg',
  //   width: 2,
  //   height: 3,
  //   alt: '입구',
  //   original: '/hospital/hospital01.jpg',
  //   caption: '입구',
  // },
  // {
  //   index: 2,
  //   src: '/hospital/hospital02.jpg',
  //   width: 3,
  //   height: 2,
  //   alt: '첫 발걸음',
  //   original: '/hospital/hospital02.jpg',
  //   caption: '첫 발걸음',
  // },
  // {
  //   index: 3,
  //   src: '/hospital/hospital03.jpg',
  //   width: 2,
  //   height: 3,
  //   alt: '대기실',
  //   original: '/hospital/hospital03.jpg',
  //   caption: '대기실',
  // },
  // {
  //   index: 4,
  //   src: '/hospital/hospital04.jpg',
  //   width: 2,
  //   height: 3,
  //   alt: '대기실',
  //   original: '/hospital/hospital04.jpg',
  //   caption: '대기실',
  // },
  // {
  //   index: 5,
  //   src: '/hospital/hospital05.jpg',
  //   width: 3,
  //   height: 2,
  //   alt: '오브제',
  //   original: '/hospital/hospital05.jpg',
  //   caption: '오브제',
  // },
  // {
  //   index: 6,
  //   src: '/hospital/hospital06.jpg',
  //   width: 2,
  //   height: 3,
  //   alt: '심리발달센터 입구',
  //   original: '/hospital/hospital06.jpg',
  //   caption: '심리발달센터 입구',
  // },
  // {
  //   index: 7,
  //   src: '/hospital/hospital07.jpg',
  //   width: 3,
  //   height: 2,
  //   alt: '안내데스크',
  //   original: '/hospital/hospital07.jpg',
  //   caption: '안내데스크',
  // },
  // {
  //   index: 8,
  //   src: '/hospital/hospital08.jpg',
  //   width: 2,
  //   height: 3,
  //   alt: '검사실',
  //   original: '/hospital/hospital08.jpg',
  //   caption: '검사실',
  // },
  // {
  //   index: 9,
  //   src: '/hospital/hospital09.jpg',
  //   width: 3,
  //   height: 2,
  //   alt: '척도검사',
  //   original: '/hospital/hospital09.jpg',
  //   caption: '척도검사',
  // },
  // {
  //   index: 10,
  //   src: '/hospital/hospital10.jpg',
  //   width: 2,
  //   height: 3,
  //   alt: '아늑한 복도',
  //   original: '/hospital/hospital10.jpg',
  //   caption: '아늑한 복도',
  // },
  // {
  //   index: 11,
  //   src: '/hospital/hospital11.jpg',
  //   width: 2,
  //   height: 3,
  //   alt: '진료실',
  //   original: '/hospital/hospital11.jpg',
  //   caption: '진료실',
  // },
  // {
  //   index: 12,
  //   src: '/hospital/hospital12.jpg',
  //   width: 2,
  //   height: 3,
  //   alt: '센터 대기석',
  //   original: '/hospital/hospital12.jpg',
  //   caption: '센터 대기석',
  // },
];

const centers = [
  // {
  //   index: 1,
  //   src: '/center/center01.jpg',
  //   width: 2,
  //   height: 3,
  //   alt: '상담실',
  //   original: '/center/center01.jpg',
  //   caption: '상담실',
  // },
  // {
  //   index: 2,
  //   src: '/center/center02.jpg',
  //   width: 3,
  //   height: 2,
  //   alt: '놀이치료실',
  //   original: '/center/center02.jpg',
  //   caption: '놀이치료실',
  // },
  // {
  //   index: 3,
  //   src: '/center/center03.jpg',
  //   width: 3,
  //   height: 2,
  //   alt: '놀이치료실 놀이기구',
  //   original: '/center/center03.jpg',
  //   caption: '놀이치료실 놀이기구',
  // },
  // {
  //   index: 4,
  //   src: '/center/center04.jpg',
  //   width: 2,
  //   height: 3,
  //   alt: '놀이치료실 놀이기구',
  //   original: '/center/center04.jpg',
  //   caption: '놀이치료실 놀이기구',
  // },
  // {
  //   index: 5,
  //   src: '/center/center05.jpg',
  //   width: 3,
  //   height: 2,
  //   alt: '놀이치료실 관찰',
  //   original: '/center/center05.jpg',
  //   caption: '놀이치료실 관찰',
  // },
];

export const photos = [...hospitals, ...centers, ...facilities];
